### ISSUE TITLE
Invalid crt linkage

### ISSUE THREAD

**Issue by myd7349** [tishion/mmLoader#18]
Hi! I am trying to add `mmloader` into `vcpkg` recently: https://github.com/microsoft/vcpkg/pull/9542, and encountered an uncompatible crt linkage issue: `mmloader` will always try to link to a dynamic version MSVC crt. To make `vcpkg` happy, I have to patch the VS project file: https://github.com/microsoft/vcpkg/pull/9542/files#diff-3a9c7d34d8547c670266e53060650a3c

I am wondering if it is possible to fix this issue in the upstrem, so that I don't need to patch the port I created.

**Comment by tishion** [comment]
hi @myd7349,  thanks for your great work! I haven't work on this project for long time, and I missed the rapid growing of vcpkg. so far i think vcpkg is a good distribution way of mmLoader.

ok let's focus on the problems now.  actually, mmLoader doesn't need any CRT dependencies at compile time and runtime. The failure of this issue [microsoft/vcpkg#9542](https://github.com/microsoft/vcpkg/pull/9542) was just caused by the configuration in the vc project file. You can change the configuration to correct ones (the vcpkg required one). 

I have addressed the problem and submit a new commit, now you can try it again.

**Comment by myd7349** [comment]
Hi! @tishion Thanks for your amazing work and kindly help. After reading your PR, it turns out that this lib only supports static link + static crt by design. So I will close this issue. :-)
