### ISSUE TITLE
Crash if some exception throw in dll

### ISSUE THREAD

**Issue by RyoHina** [tishion/mmLoader#19]
if this code in dll, it will be crashed. 
`	try
	{
		throw std::exception("d");
	}
	catch (...)
	{
		printf("some exception.\r\n");
	}`

any idea? thx

**Comment by tishion** [comment]
I guess your DLL must be linked with [/SAFESEH](https://docs.microsoft.com/en-us/cpp/build/reference/safeseh-image-has-safe-exception-handlers?view=vs-2019)

If the dll is linked with this flag (/SAFESEH), windows will validate all the exception handlers (check the handler code address to see whether it is in a valid module memory range). obviously, when you use mmloader to load the dll this validation will fail, because the code is not in a normal module address space.

Keep in mind that mmloader is designed for loading the dll which is written by yourself or at least you need to know the implementation of the dll you want to load. There are many limitations to load modules with mmloader, because mmloader doesn't equal to the original Window PE loader.

**Comment by RyoHina** [comment]
Try it yourself, It's nothing to do with /SAFESEH.
